import os
import json
# This script is to read the json files generated by endpoint.py and count statistics.
import ipdb

for filename in os.listdir(os.getcwd()):
    if filename.endswith('.json') and filename in ['13.json']:
        with open(os.path.join(os.getcwd(), filename), 'r') as f: 
            triples = json.load(f)
            print(triples[0], filename)
            num = 0
            for i in triples:
                if i["prop6"]["value"].endswith("type") :
                    num += 1
            print(f'This file {filename} has {num} which contains type in their triple, with totaly {len(triples)} graphs matched.')
            ipdb.set_trace()